### ISSUE TITLE
Could you add a LICENSE file?

### ISSUE THREAD

**Issue by hnakamur** [shogo82148/txmanager#1]
@shogo82148 First of all, thanks for sharing a nice software!

Could you add a LICENSE file?
The pages below might help for choosing a license.
- [Choosing an OSS license doesn’t need to be scary - ChooseALicense.com](http://choosealicense.com/)
- [Githubによる、オープンソースライセンスの選び方 | オープンソース・ライセンスの談話室](http://www.catch.jp/oss-license/2013/09/10/github/)

Thanks!

**Comment by shogo82148** [comment]
Thank you for your comment!

I want release it under MIT license.
Added license.txt.

**Comment by hnakamur** [comment]
Thanks!
